# This is a basic workflow to help you get started with Actions

name: poc-docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # The image name
  IMAGE_NAME: docker-robot-framework:ci

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest
    # run all our tests on each browser
    strategy:
      matrix:
        include:
          - browser: "chrome"
#           - browser: "firefox"
    env:
      BROWSER: ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
#       - name: Run Robot Tests
#         run: docker run -e ROBOT_OPTIONS="robot poc.robot" 
#         run: docker run -e ROBOT_OPTIONS="-v ENV=staging" -v `pwd`/RF/test_cases/api:/opt/robotframework/tests:Z \
        
      - name: Build image
        run: docker ps
#         run: docker build . --tag $IMAGE_NAME
#         run: docker build . --tag $IMAGE_NAME --file Dockerfile
        
#       - name: Run Robot Tests
#         run: |
#             docker run \
#             -v `pwd`/RF/test_cases/api:/opt/robotframework/tests:Z \
#             -e BROWSER=$BROWSER \
#             -e ROBOT_OPTIONS="-v ENV=staging" \

      - name: Upload run results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
